#!/bin/bash
#SBATCH --job-name="KT3 Results reproduction L=9"
#SBATCH -o ./%x.%j.%N.out
#SBATCH -e ./%x.%j.%N.err
#
#SBATCH -p E5-long
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=7-00:00:00           # day-hours:minutes:seconds
#
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=geoffroy.haeseler@ens-lyon.fr
echo "The job £{SLURM_JOB_ID} is running on these nodes:"
echo ${SLURM_NODELIST}
echo
#
cd $SLURM_SUBMIT_DIR    #go to the work / submission directory
#
module purge
module use /applis/PSMN/debian11/E5/modules/all
module load GCC/10.3.0
#
./KT3
